# Generated by Django 3.1.7 on 2021-03-13 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('card_number', models.CharField(max_length=20, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyProviders',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100, null=True)),
                ('fast_charge_cost', models.FloatField(null=True)),
                ('slow_charge_cost', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationofStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('address_postal_code', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address_region', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('private', models.SmallIntegerField(null=True)),
                ('open_hour', models.TimeField(null=True)),
                ('close_hour', models.TimeField(null=True)),
                ('area_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.area')),
            ],
        ),
        migrations.CreateModel(
            name='PointOperator',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.SmallIntegerField(null=True)),
                ('expected_time', models.IntegerField(null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.locationofstations')),
                ('provider_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.energyproviders')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('carowner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backendapp.carowner')),
                ('brand_type', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('release_year', models.CharField(max_length=4, null=True)),
                ('usable_battery_size', models.FloatField(null=True)),
                ('km_after_prev_charge', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1', null=True)),
                ('carowner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=9)),
                ('year', models.CharField(max_length=4)),
                ('total_amount', models.FloatField()),
                ('already_paid', models.SmallIntegerField()),
                ('user_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.carowner')),
            ],
        ),
        migrations.AddField(
            model_name='locationofstations',
            name='point_operator_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.pointoperator'),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(null=True)),
                ('finished_on', models.DateTimeField(null=True)),
                ('energy_amount', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('payment_method', models.CharField(choices=[('1', 'cash'), ('2', 'card'), ('3', 'month bill')], default='1', max_length=10, null=True)),
                ('protocol', models.CharField(choices=[('1', 'slow'), ('2', 'fast')], default='1', max_length=4, null=True)),
                ('station_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.station')),
                ('vehicle_carowner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.vehicle')),
            ],
        ),
    ]
