# Generated by Django 3.1.2 on 2021-03-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('apikey', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
